### ISSUE TITLE
Module parse failed: unexpected @ char

### ISSUE THREAD

**Issue by derrickmehaffy** [renrizzolo/strapi-plugin-gutenberg-editor#1]
Hello from the Strapi team o/ :wink: 

While testing this one out I noticed an error during the admin build phase, below is the stack:

```
Error: ./.cache/plugins/strapi-plugin-gutenberg-editor/admin/src/css/style.scss 1:0
Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> @import "~@wordpress/base-styles/colors";
| @import "~@wordpress/base-styles/variables";
| @import "~@wordpress/base-styles/mixins";
    at /home/dmehaffy/Development/testGutenberg/node_modules/strapi-admin/index.js:71:23
    at finalCallback (/home/dmehaffy/Development/testGutenberg/node_modules/webpack/lib/Compiler.js:257:39)
    at /home/dmehaffy/Development/testGutenberg/node_modules/webpack/lib/Compiler.js:273:13
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/dmehaffy/Development/testGutenberg/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:22:1)
    at AsyncSeriesHook.lazyCompileHook (/home/dmehaffy/Development/testGutenberg/node_modules/tapable/lib/Hook.js:154:20)
    at onCompiled (/home/dmehaffy/Development/testGutenberg/node_modules/webpack/lib/Compiler.js:271:21)
    at /home/dmehaffy/Development/testGutenberg/node_modules/webpack/lib/Compiler.js:681:15
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/dmehaffy/Development/testGutenberg/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (/home/dmehaffy/Development/testGutenberg/node_modules/tapable/lib/Hook.js:154:20)
    at /home/dmehaffy/Development/testGutenberg/node_modules/webpack/lib/Compiler.js:678:31
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/dmehaffy/Development/testGutenberg/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook (/home/dmehaffy/Development/testGutenberg/node_modules/tapable/lib/Hook.js:154:20)
    at /home/dmehaffy/Development/testGutenberg/node_modules/webpack/lib/Compilation.js:1423:35
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/dmehaffy/Development/testGutenberg/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook (/home/dmehaffy/Development/testGutenberg/node_modules/tapable/lib/Hook.js:154:20)
    at /home/dmehaffy/Development/testGutenberg/node_modules/webpack/lib/Compilation.js:1414:32
```

This testing was done on 
- Linux Mint 20 (Ubuntu 20.04)
- Node v12
- NPM v6
- SQLite
- Fresh project

I've dumped the test project into a zip here: 
[testGutenberg.zip](https://github.com/renrizzolo/strapi-plugin-gutenberg-editor/files/5996340/testGutenberg.zip)

**Comment by renrizzolo** [comment]
Oops! Thanks for testing it out @derrickmehaffy.

I now realize that I have done a custom webpack config in my testing site itself (in `admin/admin.config.js`)

Is there somewhere I can do this within the plugin?

ref: https://strapi.io/documentation/developer-docs/latest/admin-panel/custom-webpack-config.html#custom-webpack-config

**Comment by renrizzolo** [comment]
This is the custom config:
```js
module.exports = {
  webpack: (config, webpack) => {
    // add sass-loader
    config.module.rules.push({
      test: /\.scss$/,
      use: ["style-loader", "css-loader", "sass-loader"],
    });
    console.log('sass loader added')
    return config;
  },
};
```

**Comment by derrickmehaffy** [comment]
I'm not sure on that one TBH (I'm not much of a frontend dev)
